### ISSUE TITLE
Blank site with black background - user sees nothing!

### ISSUE THREAD

**Issue by COLABORATI** [joshwcomeau/Tello#3]
Really. I see nothing there, just a [black screen](https://screenshots.firefox.com/HgaNoCQnUsV14LhG/tello.tv).

Dev console errors with this:
```
TypeError: Cannot read property 'isLoading' of undefined
```
Firefox and Chromium on Ubuntu 16.04, same hap[pens with adblockers disabled.

**Comment by morajabi** [comment]
I can confirm, I'm looking into that now...

Update 1: It seems the problem is also with macOS chrome and firefox.

Update 2: The server has some problems maybe?

Update 3: Problem is here: https://github.com/joshwcomeau/Tello/blob/master/src/components/SummaryShow/SummaryShow.js#L92 
The show is not required and it can be sometimes undefined but the component doesn't contain any logic to handle that.

**Comment by deadcoder0904** [comment]
Yep not working

**Comment by deadcoder0904** [comment]
Thanks @joshwcomeau 👍 

Looking good 😍
